export const coffee = [
  {
    id: 1,
    img: "/images/expresso.svg",
    title: "Expresso tradicional",
    label: ["tradicional"],
    description: "O tradicional café feito com água quente e grãos moídos",
    value: "9,90",
  },
  {
    id: 1,
    img: "/images/expresso.svg",
    title: "Expresso tradicional",
    label: ["tradicional"],
    description: "O tradicional café feito com água quente e grãos moídos",
    value: "9,90",
  },
  {
    id: 1,
    img: "/images/expresso.svg",
    title: "Expresso tradicional",
    label: ["tradicional"],
    description: "O tradicional café feito com água quente e grãos moídos",
    value: "9,90",
  },
  {
    id: 1,
    img: "/images/expresso.svg",
    title: "Expresso tradicional",
    label: ["tradicional"],
    description: "O tradicional café feito com água quente e grãos moídos",
    value: "9,90",
  },
  {
    id: 1,
    img: "/images/expresso.svg",
    title: "Expresso tradicional",
    label: ["tradicional"],
    description: "O tradicional café feito com água quente e grãos moídos",
    value: "9,90",
  },
  {
    id: 1,
    img: "/images/expresso.svg",
    title: "Expresso tradicional",
    label: ["tradicional"],
    description: "O tradicional café feito com água quente e grãos moídos",
    value: "9,90",
  },
  {
    id: 1,
    img: "/images/expresso.svg",
    title: "Expresso tradicional",
    label: ["tradicional"],
    description: "O tradicional café feito com água quente e grãos moídos",
    value: "9,90",
  },
  {
    id: 1,
    img: "/images/expresso.svg",
    title: "Expresso tradicional",
    label: ["tradicional"],
    description: "O tradicional café feito com água quente e grãos moídos",
    value: "9,90",
  },
  {
    id: 1,
    img: "/images/expresso.svg",
    title: "Expresso tradicional",
    label: ["tradicional"],
    description: "O tradicional café feito com água quente e grãos moídos",
    value: "9,90",
  },
  {
    id: 1,
    img: "/images/expresso.svg",
    title: "Expresso tradicional",
    label: ["tradicional"],
    description: "O tradicional café feito com água quente e grãos moídos",
    value: "9,90",
  },
  {
    id: 1,
    img: "/images/expresso.svg",
    title: "Expresso tradicional",
    label: ["tradicional"],
    description: "O tradicional café feito com água quente e grãos moídos",
    value: "9,90",
  },
  {
    id: 1,
    img: "/images/expresso.svg",
    title: "Expresso tradicional",
    label: ["tradicional"],
    description: "O tradicional café feito com água quente e grãos moídos",
    value: "9,90",
  },
  {
    id: 1,
    img: "/images/expresso.svg",
    title: "Expresso tradicional",
    label: ["tradicional"],
    description: "O tradicional café feito com água quente e grãos moídos",
    value: "9,90",
  },
  {
    id: 1,
    img: "/images/expresso.svg",
    title: "Expresso tradicional",
    label: ["tradicional"],
    description: "O tradicional café feito com água quente e grãos moídos",
    value: "9,90",
  },
];
