export const coffee = [
  {
    id: 1,
    img: "/images/expresso.svg",
    title: "Expresso tradicional",
    label: ["tradicional"],
    description: "O tradicional café feito com água quente e grãos moídos",
    value: 9.9,
  },
  {
    id: 2,
    img: "/images/americano.svg",
    title: "Expresso Americano",
    label: ["tradicional"],
    description: "Expresso diluído, menos intenso que o tradicional",
    value: 9.9,
  },
  {
    id: 3,
    img: "/images/cremoso.svg",
    title: "Expresso Cremoso",
    label: ["tradicional"],
    description: "Café expresso tradicional com espuma cremosa",
    value: 9.9,
  },
  {
    id: 4,
    img: "/images/gelado.svg",
    title: "Expresso Gelado",
    label: ["tradicional", "gelado"],
    description: "Bebida preparada com café expresso e cubos de gelo",
    value: 9.9,
  },
  {
    id: 5,
    img: "/images/comLeite.svg",
    title: "Café com Leite",
    label: ["tradicional", "com leite"],
    description: "Meio a meio de expresso tradicional com leite vaporizado",
    value: 9.9,
  },
  {
    id: 6,
    img: "/images/latte.svg",
    title: "Latte",
    label: ["tradicional", "com leite"],
    description:
      "Uma dose de café expresso com o dobro de leite e espuma cremosa",
    value: 9.9,
  },
  {
    id: 7,
    img: "/images/capuccino.svg",
    title: "Capuccino",
    label: ["tradicional", "com leite"],
    description:
      "Bebida com canela feita de doses iguais de café, leite e espuma",
    value: 9.9,
  },
  {
    id: 8,
    img: "/images/macchiato.svg",
    title: "Macchiato",
    label: ["tradicional", "com leite"],
    description:
      "Café expresso misturado com um pouco de leite quente e espuma",
    value: 9.9,
  },
  {
    id: 9,
    img: "/images/mocaccino.svg",
    title: "Mocaccino",
    label: ["tradicional", "com leite"],
    description: "Café expresso com calda de chocolate, pouco leite e espuma",
    value: 9.9,
  },
  {
    id: 10,
    img: "/images/chocolate.svg",
    title: "Chocolate Quente",
    label: ["especial", "com leite"],
    description: "Bebida feita com chocolate dissolvido no leite quente e café",
    value: 9.9,
  },
  {
    id: 11,
    img: "/images/cubano.svg",
    title: "Cubano",
    label: ["especial", "alcoólico", "gelado"],
    description:
      "Drink gelado de café expresso com rum, creme de leite e hortelã",
    value: 9.9,
  },

  {
    id: 12,
    img: "/images/havaiano.svg",
    title: "Havaiano",
    label: ["especial"],
    description: "Bebida adocicada preparada com café e leite de coco",
    value: 9.9,
  },
  {
    id: 13,
    img: "/images/arabe.svg",
    title: "Árabe",
    label: ["especial"],
    description: "Bebida preparada com grãos de café árabe e especiarias",
    value: 9.9,
  },
  {
    id: 14,
    img: "/images/irlandes.svg",
    title: "Irlandês",
    label: ["especial", "alcoólico"],
    description: "Bebida a base de café, uísque irlandês, açúcar e chantilly",
    value: 9.9,
  },
];
